#  exec-once
exec-once = uwsm app -- python ~/.config/Modus/main.py
exec = pgrep -x "hypridle" > /dev/null || uwsm app -- hypridle
exec-once = uwsm app -- swww-daemon
exec-once =  wl-paste --type text --watch cliphist store
exec-once =  wl-paste --type image --watch cliphist store


# LAYER RULES FOR BLURS
layerrule = blur on, xray 0, blur_popups on, ignore_alpha 0, no_anim on, match:namespace ^modus-notifications$
layerrule = animation popin, match:namespace ^lockscreen$
layerrule = blur on, xray 0, blur_popups on, ignore_alpha 0, animation popin, match:namespace ^modus-launcher$
layerrule = blur on, ignore_alpha 0, xray 0, blur_popups on, match:namespace ^fabric$
layerrule = blur on, xray 0, blur_popups on, ignore_alpha 0, match:namespace ^modus$
layerrule = animation slide right, match:namespace ^notification-center$

# KEYBINDS

$fabricSend = fabric-cli exec modus
# Reload Modus
bind = SUPER ALT, B, exec, killall modus; uwsm-app $(python $HOME/.config/Modus/main.py)
# Message
bind = SUPER SHIFT, y, exec, $fabricSend 'app.set_css()' # Reload CSS
# # Application Switcher
bind = ALT, TAB, exec, $fabricSend 'switcher.show_switcher()'
# App Launcher
bind = SUPER, SPACE, exec, $fabricSend "launcher.show_launcher()"
# Clipboard History
bind = SUPER, V, exec, $fabricSend "launcher.show_launcher('clip')"
# Wallpapers
bind = SUPER, W, exec, $fabricSend "launcher.show_launcher('wall')"
# Random Wallpaper
bind = ALT SHIFT, W, exec, $fabricSend "launcher.show_launcher('wall random', external=True)"
# Emoji Picker
bind = SUPER, Period, exec, $fabricSend "launcher.show_launcher('em')"
# Power Menu
bind = SUPER, ESCAPE, exec, $fabricSend "launcher.show_launcher('power')"
# Toggle Caffeine
bind = SUPER SHIFT, M, exec, $fabricSend "launcher.show_launcher('caffeine on', external=True)"

