# .config/hypr/hyprland.conf
plugin {
    hyprexpo {
        columns = 2
        gap_size = 10
        bg_col = rgb(111111)
        workspace_method = center current 
# first 1 [center/first] [workspace] e.g. first 1 or center m+1

# gesture_distance = 2fg, up, 300 
# how far is the "max" for the gesture

        skip_empty = false
    }
}