# .config/hypr/hyprland.conf
plugin {
    hyprexpo {
        columns = 2
        gap_size = 10
        bg_col = rgb(111111)
        workspace_method = center current 
        skip_empty = false
        # first 1 [center/first] [workspace] e.g. first 1 or center m+1

        # gesture_distance = 2fg, up, 300 
        # how far is the "max" for the gesture 
    }
    hyprscrolling {
        column_width = 0.7                  # each column ~60% of monitor width
        fullscreen_on_one_column = true    # one column doesn't auto-fullscreen
        follow_focus = true                # view centers on focused window
        follow_min_visible = 0.1 # idk doesnt work !!!!!!!!!!

        focus_fit_method = 0               # 0=center, 1=fit column fully on screen

        explicit_column_widths = 0.5,0.67,0.7,0.8,1.0

        wrap_focus = true
        wrap_swapcol = true
    }
}