-- Generated by nwg-displays on 2026-07-28 at 21:33:49. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.06",
    position = "1920x700",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "0x0",
    scale = 1.0
})
