[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)

# Remaps the escape key to capslock
# esc = capslock

# 5.23.2026 - MACOS BINDS!
# Alt -> Ctrl ie cmd
# leftalt = layer(control)

### leftalt = leftcontrol

# meta -> alt ie option
# leftmeta = layer(alt)

### leftmeta = leftalt

# ctrl is meta/super/win bc i need it lol

### leftcontrol = leftmeta

# fn = ??
# ctrl = nothing ?